### ISSUE TITLE
Add data-driven tests for binary operators

### ISSUE THREAD

**Issue by perlun** [perlang-org/perlang#231]
#230 added data-driven tests for comparison operators. Similar work could be done elsewhere as well:

### Data driven tests with test data for all types currently supported in the language
- [x] `Addition` and `Subtraction`: #317 
- [x] `AdditionAssignment` and `SubtractionAssignment`: #319
- [x] `Exponential`: #323
- [x] `Modulo`: #324
- [x] `Multiplication` and `Division`: #318 
- [x] `Equal` and `NotEqual`: #320
- [x] `ShiftLeft` and `ShiftRight`: #325
- [x] `Less` and `LessEqual`: #321
- [x] `Greater` and `GreaterEqual`: #322

### Non-binary operators which would also be good to cover at some point
- [ ] `PostfixDecrement`
- [ ] `PostfixIncrement`

**Comment by perlun** [comment]
Not blocking the 0.1.0 release. Moving forward.

**Comment by perlun** [comment]
This has actually been done in #313, even though not all operators have full type coverage yet. I'll use this issue for tracking this now until #316 can be merged (indicating that all type combinations are fully covered for all operators).

**Comment by perlun** [comment]
I think this is accomplished well enough for 0.2.0, so I'll close this now. As for these:

> ### Non-binary operators which would also be good to cover at some point
> - [ ] `PostfixDecrement`
> - [ ] `PostfixIncrement`

...we'll cover them in a separate issue, if/when we decide to do something similar there. (`UnaryPostifxOperator` test with `UnaryPostfixOperatorData` or something.)
