### ISSUE TITLE
Support optional typing and type inference

### ISSUE THREAD

**Issue by perlun** [perlang-org/perlang#43]
# Moved to GitLab

Please continue to the new version of this issue here: https://gitlab.perlang.org/perlang/perlang/-/issues/43. The GitHub page you are currently reading will not contain the latest information on this issue.

---

### Background

Perlang is currently a _dynamically_ typed language, which has its explanation in that it has its roots as being a friendly _fork_ of [the Lox language](https://github.com/munificent/craftinginterpreters), as described in @munificent's great programming-language-tutorial ["Crafting Interpreters"](http://craftinginterpreters.com/). This has some advantages in programmer ergonomics (no need to spell out types), and it also greatly simplifies the work of implementing the interpreter.

_However_, as many of us have already experienced, this comes at a price. Purely dynamically typed languages can get frustrating to work with, especially as the project grows in complexity:

* **Harder to refactor code** (especially if your code lacks proper unit tests). With languages like Ruby, you basically need 100% test coverage for all `if`-branches in your program, for all the permutation of types being passed as variables to _all_ methods in your program. Otherwise, you are in risk of breaking your program as you refactor it.

* **Inferior performance**. If the language runtime/compiler knows the types of variables as they are flowing through your program, it can perform runtime or compile-time optimizations to increase the performance of the program. This difference is often significant; I am yet to see a dynamically typed language with performance near statically typed languages like C, C++ and Rust. Even byte-code-interpreted/JIT:ed languages like C# and Java are typically faster than the dynamically typed languages, and the static typing is one part of this. See for yourself on example of a benchmark that illustrates this: https://benchmarksgame-team.pages.debian.net/benchmarksgame/performance/binarytrees.html (The Common Lisp program is doing remarkably well there, despite Common Lisp being a dynamically typed language)

* **More frustrating to write code in**. This is of course highly subjective, many would argue to the contrary. For me personally, I find it annoying to not be able to "lock down" a method saying that _"parameter foo can only be a string, parameter bar can only be a bool"_ and so on. I tend to have that information in my head when writing the code, and being "forced" (by languages like Ruby) to throw away this information can feel frustrating, especially when you know that with some static analysis, that information could be helpful for the programming language to detect at a very early stage whether the program is "broken" or not (at least not from a "mixing types" perspective). In this sense, this is not just a subjective point. **Better adherence to the "fail-fast" paradigm"** is an objective point we could highlight here.

The idea is to implement static typing, but implement it with as little frustration as possible to the user. Think of languages like C#, F#, Haskell and modern (10+ and even 8+ to a certain degree) Java, which are all strongly typed but do their very best to not make this too annoying to the user.

### The plan for Perlang

Perlang supports, as of version 0.1.0:

* [x] _optional_ typing on variables, function return types and function parameters. Implemented as part of #54.
* [x] _type inference_ for literal expressions and other expressions where it's easy to deduce the type based on the expression(s). Implemented as part of #54.

We are planning support, hopefully by 0.2.0 or "Later":

* [ ] _type inference_ for function parameters. This is a bit non-trivial and we might need a separate tree traversal pass just for this, since the actual usage comes _later_ than when function is defined. (in essence, we need to walk the call sites before we can walk the actual code for the function, so it definitely needs a separate pass just for this)
* [ ] _type inference_ for function return types as well. An initial version of this would be to just go through the function and determine a single CLR type for any `return` statement within it. If multiple `return` statements are found with different CLR types, bail out and force the user to consciously decide on the return type.
