### ISSUE TITLE
Incorporate tests from Lox

### ISSUE THREAD

**Issue by perlun** [perlang-org/perlang#46]
# Moved to GitLab

Please continue to the new version of this issue here: https://gitlab.perlang.org/perlang/perlang/-/issues/46. The GitHub page you are currently reading will not contain the latest information on this issue.

---

There are a large number of tests at https://github.com/munificent/craftinginterpreters/tree/master/test. We implement some of them, but far from all.

We should work towards incorporating most/all of these, since they are useful for us also.

## Status

- [x] assignment - supported as of #130
- [ ] benchmark
- [ ] block 
- [ ] bool
- [ ] call
- [ ] class
- [ ] closure
- [x] comments - supported as of #141
- [ ] constructor
- [ ] empty_file.lox
- [ ] expressions
- [ ] field
- [ ] for - partially supported (#15)
- [ ] function - partially supported (#48)
- [ ] if
- [ ] inheritance
- [ ] limit
- [ ] logical_operator - partially supported (#47)
- [ ] method
- [ ] nil
- [x] number - supported as of #71
- [ ] operator - partially supported (#44, #63, #151)
- [x] precedence.lox - supported as of #4
- [ ] print
- [ ] regression
- [x] return - supported as of #51
- [ ] scanning
- [ ] string
- [ ] super
- [ ] this
- [ ] unexpected_character.lox
- [x] variable - supported as of #33
- [ ] while
